---
- include: arch.yml
  when: ansible_os_family == 'Archlinux'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Geral gtkrc file
  synchronize:
    src: files/.gtkrc-2.0
    dest: /home/{{ item.username }}/
  with_items: "{{ users }}"

- name: Specific gtkrc
  synchronize:
    src: files/.gtkrc-2.0.mine
    dest: /home/{{ item.username }}/
  with_items: "{{ users }}"

- name: Copy all icons config
  synchronize:
    src: files/
    dest: /home/{{ item.username }}/.config/
  with_items: "{{ users }}"
