---
- name: Install Thunar
  pacman: name=thunar state=latest

- name: Install Tumbler (thumbnails)
  pacman: name=tumbler state=latest

- name: Install thunar-volman (Management of removeable devices)
  pacman: name=thunar-volman state=latest

- name: Install create and modify archives
  pacman: name=file-roller state=latest

- name: Install lxappearance
  pacman: name=lxappearance state=latest

- name: Geral gtkrc file
  synchronize: src=files/.gtkrc-2.0 dest=/home/siqueira/

- name: Specific gtkrc
  synchronize: src=files/.gtkrc-2.0.mine dest=/home/siqueira/

- name: Copy all icons config
  synchronize: src=files/ dest=/home/siqueira/.config/

