---
# Keep in mind that you have to customize this files for your needs. For
# example, replace the host target by the one that you want to use.
- hosts: test_machine
  user: root
  become: yes
  roles:
    - tm_commons
    - users
    - bash_tm
    - font
    - build_env_graphics
    - igt_project
    - kernels_repos
    - virtualization
