---
- name: Create 'Repositories' directory
  file:
    path: /home/{{ item.username }}/Documents/Repositories/
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0755
    state: directory
  with_items: "{{ users }}"

- name: Create 'Repositories/kernels' directory
  file:
    path: /home/{{ item.username }}/Documents/Repositories/kernels
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0755
    state: directory
  with_items: "{{ users }}"

- name: KERNELs Clonning drm
  git:
    repo: https://anongit.freedesktop.org/git/drm/drm-misc.git
    dest: /home/{{ item.username }}/Documents/Repositories/kernels/drm
  with_items: "{{ users }}"
  become: yes
  become_user: "{{ item.username }}"

- name: KERNELs Clonning Torvalds
  git:
    repo: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
    dest: /home/{{ item.username }}/Documents/Repositories/kernels/torvalds
  with_items: "{{ users }}"
  become: yes
  become_user: "{{ item.username }}"

- name: KERNELs Clonning IIO
  git:
    repo: https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git
    dest: /home/{{ item.username }}/Documents/Repositories/kernels/iio
  with_items: "{{ users }}"
  become: yes
  become_user: "{{ item.username }}"
