---
- name: Create 'Repositories' directory
  file:
    path: /home/{{ item.username }}/Documents/Repositories/
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0755
    state: directory
  with_items: "{{ users }}"

- name: Create 'Repositories/freedesktop' directory
  file:
    path: /home/{{ item.username }}/Documents/Repositories/freedesktop
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0755
    state: directory
  with_items: "{{ users }}"

- name: FREEDESKTOP Clonning IGT
  git:
    repo: https://gitlab.freedesktop.org/drm/igt-gpu-tools.git
    dest: /home/{{ item.username }}/Documents/Repositories/freedesktop/igt-gpu-tools
  with_items: "{{ users }}"
  become: yes
  become_user: "{{ item.username }}"

- name: FREEDESKTOP Clonning libdrm
  git:
    repo: https://gitlab.freedesktop.org/mesa/drm
    dest: /home/{{ item.username }}/Documents/Repositories/freedesktop/libdrm
  with_items: "{{ users }}"
  become: yes
  become_user: "{{ item.username }}"
