---
- name: Create 'Repositories' directory
  file:
    path: /home/{{ item.username }}/Documents/Repositories/
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0755
    state: directory
  with_items: "{{ users }}"

- name: Create 'Repositories/freedesktop' directory
  file:
    path: /home/{{ item.username }}/Documents/Repositories/freedesktop
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0755
    state: directory
  with_items: "{{ users }}"

- name: Create 'Repositories/kernels' directory
  file:
    path: /home/{{ item.username }}/Documents/Repositories/kernels
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0755
    state: directory
  with_items: "{{ users }}"


- name: Create 'Repositories/compositors' directory
  file:
    path: /home/{{ item.username }}/Documents/Repositories/compositors
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0755
    state: directory
  with_items: "{{ users }}"

- name: Cloning fancy-beep project
  git:
    repo: https://github.com/rodrigosiqueira/fancy-beep.git
    dest: /home/{{ item.username }}/Documents/Repositories/fancy-beep
  with_items: "{{ users }}"

- name: Cloning kworkflow project
  git:
    repo: https://github.com/rodrigosiqueira/kworkflow.git
    dest: /home/{{ item.username }}/Documents/Repositories/kworkflow
  with_items: "{{ users }}"

- name: Cloning icons images project
  git:
    repo: https://github.com/rodrigosiqueira/icons_images.git
    dest: /home/{{ item.username }}/Documents/Repositories/icons_images
  with_items: "{{ users }}"

- name: Cloning my personal site
  git:
    repo: https://github.com/webfolder/siqueira.tech.git
    dest: /home/{{ item.username }}/Documents/Repositories/siqueira.tech
  with_items: "{{ users }}"

- name: FREEDESKTOP Clonning IGT
  git:
    repo: https://gitlab.freedesktop.org/drm/igt-gpu-tools.git
    dest: /home/{{ item.username }}/Documents/Repositories/freedesktop/igt-gpu-tools
  with_items: "{{ users }}"

- name: FREEDESKTOP Clonning libdrm
  git:
    repo: https://gitlab.freedesktop.org/mesa/drm
    dest: /home/{{ item.username }}/Documents/Repositories/freedesktop/libdrm
  with_items: "{{ users }}"

- name: KERNELs Clonning drm
  git:
    repo: https://anongit.freedesktop.org/git/drm/drm-misc.git
    dest: /home/{{ item.username }}/Documents/Repositories/kernels/drm
  with_items: "{{ users }}"

- name: KERNELs Clonning Torvalds
  git:
    repo: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
    dest: /home/{{ item.username }}/Documents/Repositories/kernels/torvalds
  with_items: "{{ users }}"

- name: KERNELs Clonning IIO
  git:
    repo: https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git
    dest: /home/{{ item.username }}/Documents/Repositories/kernels/iio
  with_items: "{{ users }}"
