- name: Update system
  pacman: update_cache=yes upgrade=yes

- name: Install common packages
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - rsync
      - curl
      - wget
      - screen
      - kmod
      - inetutils
      - net-tools # netstat and related stuff
      - vim
      - git
