---
- name: Update system
  apt: update_cache=yes upgrade=yes

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - rsync
      - curl
      - wget
      - screen
      - kmod
      - inetutils-tools
      - net-tools # netstat and related stuff
      - vim
      - git
      - rng-tools
      - haveged # TODO: we have to enable it, create a task for setup it
      - colordiff
