---
- include: arch.yml
  when: ansible_os_family == 'Archlinux'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: centos.yml
  when: ansible_os_family == 'RedHat'

- name: Create configure folder
  file: path=/home/{{ item.username }}/.config state=directory mode=0755
  with_items: "{{ users }}"

- name: Allow specified groups to sudo
  template: 
    src: sudoers.j2
    dest: /etc/sudoers.d/sudoers
    validate: 'visudo -cf %s'
    mode: 0440
  vars:
    name: "{{ item.username }}"
  with_items: "{{ users }}"
