---
- include: arch.yml
  when: ansible_os_family == 'Archlinux'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: My Xresources
  synchronize: src=files/.Xresources dest=/home/{{ item.username }}/.Xresources
  with_items: "{{ users }}"

- name: My Xinitrc
  synchronize: src=files/.xinitrc dest=/home/{{ item.username }}/.xinitrc
  with_items: "{{ users }}"

# ATTENTION
# Take a look at the path 'roles/X/files' and you'll see a bunch of X config
# files. Most of the time you can ignore it without any problem, prefer to use
# the default options; I still maintain it here due to some fancy
# configurations that my laptop required. If you know what you're doing, just
# uncomment the lines below and change whatever you want.
#- name: Copy conf files
#  synchronize: src=files/*.conf dest=/etc/X11/xorg.conf.d/
