---
- include: arch.yml
  when: ansible_os_family == 'Archlinux'

- name: Copy tint2 config files
  synchronize:
    src: files/
    dest: /home/{{ item.username }}/.config
  with_items: "{{ users }}"
  become: yes
  become_user: "{{ item.username }}"
