---
# Most of the packages in this task came from igt project.

- name: Install packages required for build things
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - base-devel
      - bc
      - moreutils # This package has the `errno -l` command. I love it!
      - ctags
      - gcc
      - flex
      - bison
      - pkg-config
      - libpciaccess
      - kmod
      - procps-ng
      - libunwind
      - libdwarf
      - zlib
      - xz
      - cairo
      - pixman
      - libudev0-shim
      - gsl
      - alsa-lib
      - xmlrpc-c
      - json-c
      - curl
      - libxrandr
      - libxv
      - xorgproto
      - python-docutils
      - valgrind
      - peg
      - meson
      - libdrm
      - libtool
      - make
      - autoconf
      - automake
      - gtk-doc
      - python-docutils
      - sudo
