---
# Most of the packages in this task came from igt project.

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: Install packages required for build things
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - bc
      - moreutils # This package has the `errno -l` command. I love it!
      - ctags
      - gcc
      - flex
      - bison
      - libpciaccess
      - kmod
      - procps-ng
      - libunwind
      - libdwarf
      - zlib
      - xz
      - cairo
      - pixman
      - libgudev1
      - gsl
      - alsa-lib
      - xmlrpc-c
      - json-c
      - curl
      - libXrandr-devel
      - libXv-devel
      - xorg-x11-proto-devel
      - python-docutils
      - valgrind
      - meson
      - libdrm
      - libtool
      - make
      - autoconf
      - automake
      - gtk-doc
      - python-docutils
      - sudo
