---
# Most of the packages in this task came from igt project.

- name: Install packages required for build things
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - build-essential
      - bc
      - moreutils # This package has the `errno -l` command. I love it!
      - exuberant-ctags
      - gcc
      - flex
      - bison
      - pkg-config
      - libpciaccess-dev
      - kmod
      - libprocps-dev
      - libunwind-dev
      - libdwarf-dev
      - xz-utils
      - libghc-cairo-dev
      - libpixman-1-dev
      - libgudev-1.0-0
      - libgsl-dev
      - libdssialsacompat-dev
      - libxmlrpc-core-c3-dev
      - libjson-c-dev
      - curl
      - libxrandr-dev
      - libxv-dev
      - x11proto-dev
      - python-docutils
      - valgrind
      - peg
      - meson
      - libdrm-dev
      - autotools-dev
      - make
      - autoconf
      - automake
      - gtk-doc-tools
      - sudo
