- name: Install basic devel packages
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - base-devel
      - bc
      - moreutils # This package has the `errno -l` command. I love it!
      - geany
      - ctags
      - vim
