- name: Install basic devel packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - build-essential
      - bc
      - moreutils # This package has the `errno -l` command. I love it!
      - geany
      - exuberant-ctags
      - vim
      - libncurses-dev # Kernel: menus
      - libelf-dev # Kernel: orc stuff
      - libssl-dev # Kernel: openssl stuff
      - flex
      - bison
      - kernel-package
      - autoconf
