- name: Install automount packages
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - autofs # A Kernel-based automounter
      - gvfs # Virtual filesystem implementation for GIO
      - udisks2 # Disk manager service
      - ntfs-3g

