---
# TODO: This looks like generic between Arch and Debian
- name: Install git
  package:
    name: git
    state: latest

- name: Copy git prompt to .config
  synchronize: src=files/git-prompt.sh dest=/home/{{ item.username }}/.config
  with_items: "{{ users }}"

- name: Copy git completition to .config
  synchronize: src=files/git-completion.bash dest=/home/{{ item.username }}/.config
  with_items: "{{ users }}"
