---
- include: arch.yml
  when: ansible_os_family == 'Archlinux'

- include: debian.yml
  when: ansible_os_family == 'Debian'

# I added the condition of only copy the file if there is no file already.
# However, this is not a good idea all of the time; keep in mind that during
# the configuration process you may want to manually remove the files under
# '.config' directory. (comment related with the below tasks)

# XXX: I consciously hardcoded my default username, since I was in rush to
# finish this playbook. The problem to be fixed here is: we cannot have
# 'with_item' and 'register' together. Probably, we have to use with_together
# here.
- name: Check if there is an openbox configuration
  register: sync_config_dir
  stat:
    path: /home/siqueira/.config/openbox/menu.xml

- name: Basic openbox configure files
  when: sync_config_dir.stat.exists == false
  synchronize:
    src: files/
    dest: /home/{{ item.username }}/.config
  with_items: "{{ users }}"
