---
- name: Install Openbox
  pacman: name=openbox state=latest

- name: Install obconf
  pacman: name=obconf state=latest

- name: Basic openbox configure files ({{ default_user }})
  synchronize: src=files/ dest=/home/{{ default_user }}/.config
