---
- name: Install virtualization packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - libvirt-dev
      - qemu
      - qemu-utils
      - virt-manager
      - virt-viewer
      - samba
      - cifs-utils
      - ssh
      - qemu-kvm
