- name: Update system
  apt: update_cache=yes upgrade=yes

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - lxterminal
      - rsync
      - xterm
      - firefox
      - alsa-utils
      - curl
      - wget
      - screen
      - redshift
      - feh
      - xmlto
      - docbook-xsl
      - kmod
      - inetutils-tools
      - xfce4-power-manager
      - vim
      - xorg
      - xserver-xorg-core
      - net-tools # netstat and related stuff
      - rng-tools
      - haveged # TODO: we have to enable it, create a task for setup it
      - elinks
      - abook
      - lshw
      - htop
      - sudo
