---
- include: arch.yml
  when: ansible_os_family == 'Archlinux'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Create configure folder
  file: path=/home/{{ item.username }}/.config/ state=directory mode=0755
  with_items: "{{ users }}"

- name: My default background
  synchronize: src=files/space_invader.png dest=/home/{{ item.username }}/.config/
  with_items: "{{ users }}"
